namespace APICore.API.Utils
{
    /// <summary>
    /// Etiquetas globales por defecto (alimentos, electrónica, hogar, etc.).
    /// </summary>
    internal static class DefaultTagsSeedData
    {
        /// <summary>Name, Slug, Color</summary>
        internal static readonly (string Name, string Slug, string Color)[] Tags =
        {
            ("Vegano", "vegano", "#639922"),
            ("Vegetariano", "vegetariano", "#639922"),
            ("Sin gluten", "sin-gluten", "#639922"),
            ("Sin lactosa", "sin-lactosa", "#639922"),
            ("Sin azúcar", "sin-azucar", "#639922"),
            ("Orgánico", "organico", "#639922"),
            ("Artesanal", "artesanal", "#639922"),
            ("Sin conservantes", "sin-conservantes", "#639922"),
            ("Bajo en calorías", "bajo-en-calorias", "#639922"),
            ("Alto en proteínas", "alto-en-proteinas", "#639922"),
            ("Congelado", "congelado", "#639922"),
            ("Fresco", "fresco", "#639922"),
            ("Perecedero", "perecedero", "#639922"),
            ("Picante", "picante", "#639922"),
            ("Sin alcohol", "sin-alcohol", "#639922"),
            ("Bebida alcohólica", "bebida-alcoholica", "#639922"),
            ("Para celíacos", "para-celiacos", "#639922"),
            ("Keto", "keto", "#639922"),
            ("Sin mariscos", "sin-mariscos", "#639922"),
            ("Apto diabéticos", "apto-diabeticos", "#639922"),
            ("Nuevo en caja", "nuevo-en-caja", "#185FA5"),
            ("Reacondicionado", "reacondicionado", "#185FA5"),
            ("Con garantía", "con-garantia", "#185FA5"),
            ("Inalámbrico", "inalambrico", "#185FA5"),
            ("Bluetooth", "bluetooth", "#185FA5"),
            ("WiFi", "wifi", "#185FA5"),
            ("4G", "4g", "#185FA5"),
            ("5G", "5g", "#185FA5"),
            ("USB-C", "usb-c", "#185FA5"),
            ("Recargable", "recargable", "#185FA5"),
            ("Smart", "smart", "#185FA5"),
            ("Compatible iOS", "compatible-ios", "#185FA5"),
            ("Compatible Android", "compatible-android", "#185FA5"),
            ("Gaming", "gaming", "#185FA5"),
            ("4K", "4k", "#185FA5"),
            ("Full HD", "full-hd", "#185FA5"),
            ("Táctil", "tactil", "#185FA5"),
            ("Portátil", "portatil", "#185FA5"),
            ("Con cámara", "con-camara", "#185FA5"),
            ("Resistente al agua", "resistente-al-agua", "#185FA5"),
            ("Para cocina", "para-cocina", "#BA7517"),
            ("Para baño", "para-bano", "#BA7517"),
            ("Para sala", "para-sala", "#BA7517"),
            ("Para dormitorio", "para-dormitorio", "#BA7517"),
            ("Bajo consumo", "bajo-consumo", "#BA7517"),
            ("Silencioso", "silencioso", "#BA7517"),
            ("Compacto", "compacto", "#BA7517"),
            ("Gran capacidad", "gran-capacidad", "#BA7517"),
            ("Multifunción", "multifuncion", "#BA7517"),
            ("Con temporizador", "con-temporizador", "#BA7517"),
            ("Control remoto", "control-remoto", "#BA7517"),
            ("Automático", "automatico", "#BA7517"),
            ("Ecológico", "ecologico", "#BA7517"),
            ("Fácil limpieza", "facil-limpieza", "#BA7517"),
            ("Inoxidable", "inoxidable", "#BA7517"),
            ("Antiadherente", "antiadherente", "#BA7517"),
            ("Para exteriores", "para-exteriores", "#BA7517"),
            ("Decorativo", "decorativo", "#BA7517"),
            ("Hecho a mano", "hecho-a-mano", "#BA7517"),
            ("Importado", "importado", "#BA7517"),
            ("Natural", "natural", "#D4537E"),
            ("Hipoalergénico", "hipoalergenico", "#D4537E"),
            ("Dermatológico", "dermatologico", "#D4537E"),
            ("Sin parabenos", "sin-parabenos", "#D4537E"),
            ("Cruelty free", "cruelty-free", "#D4537E"),
            ("Para piel seca", "para-piel-seca", "#D4537E"),
            ("Para piel grasa", "para-piel-grasa", "#D4537E"),
            ("Para cabello rizado", "para-cabello-rizado", "#D4537E"),
            ("Medicamento", "medicamento", "#D4537E"),
            ("Suplemento", "suplemento", "#D4537E"),
            ("Vitaminas", "vitaminas", "#D4537E"),
            ("Sin fragancia", "sin-fragancia", "#D4537E"),
            ("FPS solar", "fps-solar", "#D4537E"),
            ("Antibacterial", "antibacterial", "#D4537E"),
            ("Para bebés", "para-bebes", "#D4537E"),
            ("Talla única", "talla-unica", "#854F0B"),
            ("Tallas grandes", "tallas-grandes", "#854F0B"),
            ("Unisex", "unisex", "#854F0B"),
            ("Para hombre", "para-hombre", "#854F0B"),
            ("Para mujer", "para-mujer", "#854F0B"),
            ("Para niños", "para-ninos", "#854F0B"),
            ("Temporada verano", "temporada-verano", "#854F0B"),
            ("Temporada invierno", "temporada-invierno", "#854F0B"),
            ("100% algodón", "100-algodon", "#854F0B"),
            ("Impermeable", "impermeable", "#854F0B"),
            ("Lavable a máquina", "lavable-a-maquina", "#854F0B"),
            ("Edición limitada", "edicion-limitada", "#854F0B"),
            ("Para gym", "para-gym", "#0F6E56"),
            ("Al aire libre", "al-aire-libre", "#0F6E56"),
            ("Natación", "natacion", "#0F6E56"),
            ("Ciclismo", "ciclismo", "#0F6E56"),
            ("Running", "running", "#0F6E56"),
            ("Yoga", "yoga", "#0F6E56"),
            ("Fútbol", "futbol", "#0F6E56"),
            ("Profesional", "profesional", "#0F6E56"),
            ("Amateur", "amateur", "#0F6E56"),
            ("Para niños deporte", "para-ninos-deporte", "#0F6E56"),
            ("Oferta", "oferta", "#A32D2D"),
            ("Nuevo", "nuevo", "#A32D2D"),
            ("Más vendido", "mas-vendido", "#A32D2D"),
            ("Última unidad", "ultima-unidad", "#A32D2D"),
            ("Envío incluido", "envio-incluido", "#A32D2D"),
            ("Solo online", "solo-online", "#A32D2D"),
            ("Exclusivo", "exclusivo", "#A32D2D"),
            ("Segunda mano", "segunda-mano", "#A32D2D"),
            ("Sin stock en tienda", "sin-stock-en-tienda", "#A32D2D"),
            ("Digital", "digital", "#534AB7"),
            ("Físico", "fisico", "#534AB7"),
            ("Descargable", "descargable", "#534AB7"),
            ("Suscripción", "suscripcion", "#534AB7"),
            ("Pack / Combo", "pack-combo", "#534AB7"),
            ("Por unidad", "por-unidad", "#534AB7"),
            ("Por kg", "por-kg", "#534AB7"),
            ("Por litro", "por-litro", "#534AB7"),
            ("Por metro", "por-metro", "#534AB7"),
            ("Servicio", "servicio", "#534AB7"),
            ("Personalizable", "personalizable", "#534AB7"),
        };
    }
}
